# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_users_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='text',
        ),
        migrations.AddField(
            model_name='users',
            name='confirm_password',
            field=models.CharField(default='enter the password again', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='enter the password', max_length=20),
            preserve_default=False,
        ),
    ]
