# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_remove_users_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='confirm_password',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
