# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0008_auto_20171224_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirm_password',
        ),
    ]
