# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0009_remove_users_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='no photo', upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
