# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0010_users_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
    ]
