# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0013_auto_20180108_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
